# Generated by Django 6.1.1 on 2026-09-29 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SYSTEM_ADMIN', 'System Admin'), ('OWNER', 'Owner')], default='OWNER', max_length=20),
        ),
    ]
